using AccountDocApi.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace AccountDocApi.Data
{
    public static class DbInitializer
    {
        public static async Task InitializeAsync(AppDbContext context)
        {
            // Execute table creation DDL explicitly for Supabase compatibility
            var createTablesSql = @"
                CREATE TABLE IF NOT EXISTS ""Accounts"" (
                    ""AccountNo"" VARCHAR(50) PRIMARY KEY,
                    ""CustomerId"" VARCHAR(50) NOT NULL,
                    ""CustomerName"" VARCHAR(200) NOT NULL,
                    ""AccountType"" VARCHAR(50),
                    ""AccountStatus"" VARCHAR(50),
                    ""Branch"" VARCHAR(100)
                );

                CREATE TABLE IF NOT EXISTS ""Documents"" (
                    ""DocumentId"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AccountNo"" VARCHAR(50) NOT NULL REFERENCES ""Accounts""(""AccountNo"") ON DELETE CASCADE,
                    ""DocumentType"" VARCHAR(50) NOT NULL,
                    ""DocumentName"" VARCHAR(255) NOT NULL,
                    ""DocumentUrl"" VARCHAR(500),
                    ""CreatedDate"" TIMESTAMP WITH TIME ZONE NOT NULL,
                    ""FileContent"" BYTEA
                );
            ";

            await context.Database.ExecuteSqlRawAsync(createTablesSql);

            // Seed Accounts if not present
            if (!await context.Accounts.AnyAsync())
            {
                var accounts = new[]
                {
                    new Account
                    {
                        AccountNo = "ACC1001",
                        CustomerId = "CUST-8832",
                        CustomerName = "Ahmed Hassan",
                        AccountType = "Savings",
                        AccountStatus = "Active",
                        Branch = "Cairo Main Branch"
                    },
                    new Account
                    {
                        AccountNo = "ACC1002",
                        CustomerId = "CUST-9941",
                        CustomerName = "Sara Mahmoud",
                        AccountType = "Checking",
                        AccountStatus = "Active",
                        Branch = "Alexandria Branch"
                    },
                    new Account
                    {
                        AccountNo = "ACC1003",
                        CustomerId = "CUST-7715",
                        CustomerName = "Mohamed Ali",
                        AccountType = "Corporate",
                        AccountStatus = "Pending",
                        Branch = "Giza Branch"
                    }
                };

                await context.Accounts.AddRangeAsync(accounts);
                await context.SaveChangesAsync();
            }

            // Seed Documents if not present
            if (!await context.Documents.AnyAsync())
            {
                byte[] sampleSignatureBytes1 = Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==");
                byte[] sampleSignatureBytes2 = Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==");

                var documents = new[]
                {
                    new Document
                    {
                        AccountNo = "ACC1001",
                        DocumentType = "Signature",
                        DocumentName = "Signature_ACC1001.png",
                        DocumentUrl = "http://localhost:5000/documents/signatures/ACC1001.png",
                        CreatedDate = new DateTime(2026, 9, 21, 10, 0, 0, DateTimeKind.Utc),
                        FileContent = sampleSignatureBytes1
                    },
                    new Document
                    {
                        AccountNo = "ACC1002",
                        DocumentType = "Signature",
                        DocumentName = "Signature_ACC1002.png",
                        DocumentUrl = "http://localhost:5000/documents/signatures/ACC1002.png",
                        CreatedDate = new DateTime(2026, 9, 21, 11, 30, 0, DateTimeKind.Utc),
                        FileContent = sampleSignatureBytes2
                    },
                    new Document
                    {
                        AccountNo = "ACC1003",
                        DocumentType = "Signature",
                        DocumentName = "Signature_ACC1003.png",
                        DocumentUrl = "http://localhost:5000/documents/signatures/ACC1003.png",
                        CreatedDate = new DateTime(2026, 9, 21, 12, 15, 0, DateTimeKind.Utc),
                        FileContent = sampleSignatureBytes1
                    }
                };

                await context.Documents.AddRangeAsync(documents);
                await context.SaveChangesAsync();
            }
        }
    }
}
